# Generated by Django 2.2.1 on 2019-05-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер зала')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('trailer_url', models.CharField(max_length=200, verbose_name='Ссылка на трейлер')),
                ('producer', models.TextField(verbose_name='Режиссер')),
                ('actors', models.TextField(verbose_name='Актеры')),
                ('age_rate', models.IntegerField(verbose_name='Возрастной рейтинг')),
                ('release_date', models.DateField(verbose_name='Дата премьеры')),
                ('poster', models.ImageField(upload_to='', verbose_name='Постер')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Movie', verbose_name='Фильм')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Номер ряда')),
                ('seat_number', models.IntegerField(verbose_name='Номер места')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hall', verbose_name='Зал')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=30, verbose_name='Код брони')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Seat', verbose_name='Место')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
